const data = [
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'STEM',
        room: '123',
        floor: '1',
        people: '4',
        barricaded: true,
    },
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'Arts',
        room: '123',
        floor: '1',
        people: '4',
        barricaded: true,
    },
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'Arts',
        room: '123',
        floor: '1',
        people: '4',
        barricaded: true,
    },
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'STEM',
        room: '123',
        floor: '2',
        people: '4',
        barricaded: true,
    },
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'Business',
        room: '123',
        floor: '2',
        people: '4',
        barricaded: true,
    },
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'STEM',
        room: '123',
        floor: '1',
        people: '4',
        barricaded: true,
    },
    
    {
        name: 'Rajmeet',
        phone: '1234567890',
        location: 'STEM',
        room: '123',
        floor: '1',
        people: '4',
        barricaded: true,
    },

];